import Head from "next/head";

interface HomeProps {
  content: {
    title: string;
  };
}

export default function Home({ content }: HomeProps) {
  const { title } = content;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{title}</div>
    </>
  );
}

export const getStaticProps = async () => {
  const BASE_URL = "http://localhost:1337/api/about";

  const response = await fetch(BASE_URL);
  const { data } = await response.json();

  return {
    props: {
      content: data,
    },
    revalidate: 30,
  };
};
